package com.gonnect.aws.dynomodb.dq.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import javax.validation.constraints.NotNull;
import java.sql.Timestamp;

/**
 * Domain model for DQ registration
 */
@DynamoDBTable(tableName = "DqRegistration")
@EqualsAndHashCode
@ToString
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DqRegistration {

    private String dataSourceName;
    private Timestamp startDateTime;
    private Timestamp endDateTime;
    private long sourceCount = -1;
    private long sourceRejectionCount = -1;

    @DynamoDBHashKey(attributeName = "DataSourceName")
    @DynamoDBAutoGeneratedKey
    @NotNull(message = "Data Source Name must not be empty")
    public String getDataSourceName() {

        return dataSourceName;
    }

    @DynamoDBAttribute(attributeName = "StartDateTime")
    public Timestamp getStartDateTime() {
        return startDateTime;
    }

    @DynamoDBAttribute(attributeName = "EndDateTime")
    public Timestamp getEndDateTime() {
        return endDateTime;
    }

    @DynamoDBAttribute(attributeName = "SourceCount")
    public long getSourceCount() {
        return sourceCount;
    }

    @DynamoDBAttribute(attributeName = "SourceRejectionCount")
    public long getSourceRejectionCount() {
        return sourceRejectionCount;
    }
}

